version: '3'
services:
  mysql:
    container_name: mysql-database
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mario
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - networkmysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    container_name: mario-frontend
    build:
      context: ./mario-frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - networkmysql

  backend:
    container_name: mario-backend
    build:
      context: ./mario-back
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=mario
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - networkmysql
    depends_on:
      - mysql
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  networkmysql:
volumes:
  mysql_data:
